# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Automation Workflow

on:
  schedule:
    - cron: 30 03 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running Test Automation Framework with Maven
        run: mvn test -X "-Dbrowser=chrome" "-DisLambdaTest=true" "-DisHeadless=false"

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Test logs
          path: logs/

      - name: Upload HTML Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: html-report
          path: report.html

      - name: Test Execution Status
        if: always()
        run: echo "Test Execution Completed"

      - name: Copy report to gh.actions.pages folder
        if: always()
        run: |
          echo "Creating the 'public/extent-reports-githubActions' directory..."
          mkdir -p public/extent-reports-githubActions
          echo "Copying report.html to the folder..."
          cp report.html public/extent-reports-githubActions/
          echo "Listing contents of the folder to verify the copy..."
          ls -l public/extent-reports-githubActions
          
      - name: Deploy to GitHub Actions Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.7.1
        with:
          folder: public/extent-reports-githubActions
          token: ${{ secrets.PersonalAccessToken }}
          clean: true
        
